import type { PixelGrid } from '../pixel';

/**
 * FOOD LOOT — 32x32, drawn against OBJECT_PALETTE.
 *
 * Redrawn against the conventions that separate published pixel food from
 * programmer art:
 *
 *   PLATES. Almost every item sits on a dish. It grounds the object, gives the
 *   whole set one consistent silhouette base, and stops food looking like it is
 *   floating an inch above the carpet.
 *
 *   HUE-MATCHED OUTLINES. The dark end of each material's own ramp does the
 *   outlining. A black keyline around everything is what made the old set look
 *   like stickers.
 *
 *   RAMPS, NOT PAIRS. Three or four steps per material, lit from the upper
 *   left, with a 1-2px near-white specular where the surface is glossy.
 *
 * These are lures the player drops to steer guests, so each silhouette has to
 * be readable from across a dark room at one tile.
 */

const PIZZA: PixelGrid = [
  '................................',
  '................................',
  '................................',
  '................................',
  '.........jjjjjjjjjjjjjj.........',
  '.......jjIIIIIIIIIIIIIIjj.......',
  '......jIIiiiiiiiiiiiiiiIIj......',
  '.....jIiiEEEEEEEEEEEEiiiiIj.....',
  '....jIiiEBBBBBBBBBBBBEiiiiIj....',
  '....jIiEBqqqqqqqqqqqqBEiiiIj....',
  '....jIiBqbbbbbbbbbbbbqBiiiIj....',
  '.....jIBqbffffffffffbqBiiIj.....',
  '.....jIBbfgffRRffffffbBiiIj.....',
  '......jBbffpRRRpffffbbBiIj......',
  '......jBbfffpRRpfffffbBiIj......',
  '.......jBbffffffgfffbBiIj.......',
  '.......jBbfffffffffbbBiIj.......',
  '........jBbffRRffffbBiIj........',
  '........jBbfpRRRpfbbBiIj........',
  '.........jBbfpRRpfbBiIj.........',
  '.........jBbffffbbBiIj..........',
  '..........jBbffffbBiIj..........',
  '..........jBbfffbBiIj...........',
  '...........jBbfbbBiIj...........',
  '...........jBbfbBiIj............',
  '............jBbbBiIj............',
  '............jBBBiIj.............',
  '.............jIIIj..............',
  '..............jjj...............',
  '...........nnnnnnnnn............',
  '................................',
  '................................',
];

const NACHOS: PixelGrid = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '..............BB................',
  '.............BqqB...............',
  '............BqggqB..BB..........',
  '...........Bqgffgqb.BqB.........',
  '......BB...Bqffffqb.BqgB........',
  '.....BqqB..Bbffffbb.Bqgb........',
  '....BqggqB.BbfffbbB.Bbfb........',
  '....BqffgqBBbbffbB..Bbfb........',
  '....Bqffffqbbbbbb...Bbbb........',
  '....Bbffffbbbb......BbbB........',
  '.....Bbffbbbb.......Bbb.........',
  '......Bbbbb.........BB..........',
  '.....jjjjjjjjjjjjjjjjjj.........',
  '....jEEEEEEEEEEEEEEEEEEj........',
  '....jiiiiiiiiiiiiiiiiiij........',
  '....jIiiiiiiiiiiiiiiiIIj........',
  '.....jIIiiiiiiiiiiiIIIj.........',
  '......jIIIIIIIIIIIIIIj..........',
  '.......jjIIIIIIIIIIjj...........',
  '.........jjjjjjjjjj.............',
  '.......nnnnnnnnnnnnnnn..........',
  '................................',
  '................................',
  '................................',
];

const CHIPS: PixelGrid = [
  '................................',
  '................................',
  '................................',
  '................................',
  '.........RRRRRRRRRRRR...........',
  '........RpppppppppppR...........',
  '.......RprrrrrrrrrrrpR..........',
  '.......RprrrrrrrrrrrrpR.........',
  '.......RprrrrrrrrrrrrpR.........',
  '.......RprrEEEEEEEErrpR.........',
  '.......RprEiiiiiiiiErpR.........',
  '.......RprEifgggfiiErpR.........',
  '.......RprEiffgffiiErpR.........',
  '.......RprEiiffiiiiErpR.........',
  '.......RprEiiiiiiiiErpR.........',
  '.......RprrEEEEEEEErrpR.........',
  '.......RprrrrrrrrrrrrpR.........',
  '.......RprrrrrrrrrrrrpR.........',
  '.......RprrrrrrrrrrrrpR.........',
  '.......RprrrrRRRRrrrrpR.........',
  '.......RprrrRRRRRRrrrpR.........',
  '.......RprrrrRRRRrrrrpR.........',
  '.......RprrrrrrrrrrrrpR.........',
  '.......RRrrrrrrrrrrrrRR.........',
  '........RRRRRRRRRRRRRR..........',
  '.........RRRRRRRRRRRR...........',
  '........nnnnnnnnnnnnnn..........',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
];

const SODA: PixelGrid = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '.............ZZZZZZ.............',
  '............ZxxxxxxZ............',
  '............ZzzzzzzZ............',
  '............ZZZZZZZZ............',
  '...........ZRpppppprZ...........',
  '...........RpxrrrrrpR...........',
  '...........RpxrrrrrpR...........',
  '...........RpxrrrrrpR...........',
  '...........REEEEEEEpR...........',
  '...........RiiiiiiiER...........',
  '...........RiffgfffiR...........',
  '...........RifgggffiR...........',
  '...........RiffgfffiR...........',
  '...........RiiiiiiiiR...........',
  '...........REEEEEEEER...........',
  '...........RpxrrrrrrR...........',
  '...........RpxrrrrrrR...........',
  '...........RpxrrrrrrR...........',
  '...........RprrrrrrRR...........',
  '...........RRrrrrRRR............',
  '...........ZRRRRRRRZ............',
  '............ZZZZZZZZ............',
  '...........nnnnnnnnnn...........',
  '................................',
  '................................',
  '................................',
  '................................',
];

const LEFTOVERS: PixelGrid = [
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '.........jjjjjjjjjjjjjj.........',
  '........jEEEEEEEEEEEEEEj........',
  '.......jEiiiiiiiiiiiiiiEj.......',
  '.......jEiIIIIIIIIIIIIiEj.......',
  '.......jEiIjjjjjjjjjjIiEj.......',
  '.......jjjjjjjjjjjjjjjjjj.......',
  '......jEEEEEEEEEEEEEEEEEEj......',
  '......jEiiiiiiiiiiiiiiiiEj......',
  '......jEiirrrrrrrrrrrriiEj......',
  '......jEirpppppppppppprIEj......',
  '......jEirpEEEEEEEEEEprIEj......',
  '......jEirpEiiiiiiiiEprIEj......',
  '......jEirpEifffffiiEprIEj......',
  '......jEirpEiiiiiiiiEprIEj......',
  '......jEirpEEEEEEEEEEprIEj......',
  '......jEirpppppppppppprIEj......',
  '......jEiirrrrrrrrrrrriiEj......',
  '......jEIiiiiiiiiiiiiiiIEj......',
  '......jEIIIIIIIIIIIIIIIIEj......',
  '......jjIIIIIIIIIIIIIIIIjj......',
  '.......jjjjjjjjjjjjjjjjjj.......',
  '......nnnnnnnnnnnnnnnnnnnn......',
  '................................',
  '................................',
  '................................',
  '................................',
];

const CAKE: PixelGrid = [
  '................................',
  '................................',
  '..............GG................',
  '.............GffG...............',
  '.............GffG...............',
  '..............ff................',
  '.............jiij...............',
  '.............jiij...............',
  '.............jiij...............',
  '........jjjjjjjjjjjjjj..........',
  '.......jEEEEEEEEEEEEEEj.........',
  '.......jEiiiiiiiiiiiiEj.........',
  '.......jEiEEEEEEEEEEiEj.........',
  '.......jEiEppppppppEiEj.........',
  '.......jEiErrrrrrrrEiEj.........',
  '.......jEiEEEEEEEEEEiEj.........',
  '.......jEiiiiiiiiiiiiEj.........',
  '.......jEiIIIIIIIIIIIEj.........',
  '.......jEiErrrrrrrrEiEj.........',
  '.......jEiEpppppppprEij.........',
  '.......jEiEEEEEEEEEEiEj.........',
  '.......jEiiiiiiiiiiiiEj.........',
  '.......jEIIIIIIIIIIIIEj.........',
  '.......jjIIIIIIIIIIIIjj.........',
  '......jjjjjjjjjjjjjjjjjj........',
  '.....jEEEEEEEEEEEEEEEEEEj.......',
  '.....jIIIIIIIIIIIIIIIIIIj.......',
  '......jjIIIIIIIIIIIIIIjj........',
  '........jjjjjjjjjjjjjj..........',
  '......nnnnnnnnnnnnnnnnnn........',
  '................................',
  '................................',
];

export const FOOD = {
  pizza: PIZZA,
  nachos: NACHOS,
  chips: CHIPS,
  soda: SODA,
  leftovers: LEFTOVERS,
  cake: CAKE,
} as const;

export type FoodId = keyof typeof FOOD;
